pivnet_token: <CHANGE_ME>
github_token: <CHANGE_ME>
github_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
        <CHANGE_ME>
  -----END RSA PRIVATE KEY-----

vcenter_host: <CHANGE_ME>
vcenter_usr: <CHANGE_ME>
vcenter_pwd: <CHANGE_ME>
vcenter_data_center: Datacenter

## Ops Manager installation meta data
om_data_store: <CHANGE_ME>
om_host: <CHANGE_ME>
om_usr: <CHANGE_ME>
om_pwd: <CHANGE_ME>
om_ssh_pwd: <CHANGE_ME>
om_decryption_pwd: <CHANGE_ME>
om_ntp_servers: <CHANGE_ME>
om_dns_servers: <CHANGE_ME>
om_gateway: <CHANGE_ME>
om_netmask: <CHANGE_ME>
om_ip: <CHANGE_ME>

om_vm_network: <CHANGE_ME>
om_vm_name: <CHANGE_ME>
om_resource_pool: <CHANGE_ME>

disk_type: <CHANGE_ME>
om_vm_power_state: true

storage_names: <CHANGE_ME>

## AZ configuration for Ops Director
az_1_name: INFRA-AZ
az_2_name: DEPLOYMENT-AZ
az_3_name: SERVICES-AZ

az_1_cluster_name: Cluster
az_2_cluster_name: Cluster
az_3_cluster_name: Cluster

az_1_rp_name: MGMT-RP
az_2_rp_name: ERT-RP
az_3_rp_name: SERVICES-RP

ntp_servers: <CHANGE_ME>
ops_dir_hostname:

## Network configuration for Ops Director
infra_network_name: <CHANGE_ME>
infra_vsphere_network: <CHANGE_ME>
infra_nw_cidr: <CHANGE_ME>
infra_excluded_range: <CHANGE_ME>

infra_nw_dns: <CHANGE_ME>
infra_nw_gateway: <CHANGE_ME>
infra_nw_az: <CHANGE_ME>

deployment_network_name: <CHANGE_ME>
deployment_vsphere_network:
deployment_nw_cidr:
deployment_excluded_range:
deployment_nw_dns:
deployment_nw_gateway:
deployment_nw_az:

services_network_name: <CHANGE_ME>
services_vsphere_network:
services_nw_cidr:
services_excluded_range:
services_nw_dns:
services_nw_gateway:
services_nw_az:

dynamic_services_network_name: <CHANGE_ME>
dynamic_services_vsphere_network:
dynamic_services_nw_cidr:
dynamic_services_excluded_range:
dynamic_services_nw_dns:
dynamic_services_nw_gateway:
dynamic_services_nw_az:

loggregator_endpoint_port: 443

## Syslog endpoint configuration goes here
syslog_host:
syslog_port:
syslog_protocol:

## Wildcard domain certs go here
ssl_cert:
ssl_private_key:

disable_http_proxy: false

## TCP routing and routing services
tcp_routing: disable
tcp_routing_ports:
route_services: enable
ignore_ssl_cert_verification: true

## SMTP configuration goes here
smtp_from:
smtp_address:
smtp_port:
smtp_user:
smtp_pwd:
smtp_auth_mechanism:

# Valid values are internal, ldap, saml
# If using ldap, provide values for LDAP configuration below and
# add ldap-properties.json to tasks/config-ert/task.sh#CF_PROPERTIES section
uaa_user_account_store: internal
apps_manager_company_name: <CHANGE_ME>
allow_app_ssh_access: true

#valid vlaues are enable, disable
enable_tcp_routing_reserved_ports: disable

## LDAP Configuration goes here
ldap_url:
ldap_user:
ldap_pwd:
search_base:
search_filter:
group_search_base:
group_search_filter:
mail_attribute_name:
first_name_attribute:
last_name_attribute:


## Deployment domain names
system_domain: <CHANGE_ME>
apps_domain: <CHANGE_ME>

## valid valiues are true, false
skip_cert_verify: <CHANGE_ME>

## Static IP's for the following jobs
ha_proxy_ips: 10.193.158.250
router_static_ips:
tcp_router_static_ips:
ssh_static_ips:

## Target email address to receive mysql monitor notifications - required for 1.9
mysql_monitor_email: <CHANGE_ME>

## Default resource configuration
consul_server_instances: 1
nats_instances: 1
etcd_tls_server_instances: 1
nfs_server_instances: 1
mysql_proxy_instances: 1
mysql_instances: 1
backup_prepare_instances: 0
# Fill this in if you are using PostGres db
ccdb_instances: 0
uaadb_instances: 0
uaa_instances: 1
cloud_controller_instances: 1
ha_proxy_instances: 1
router_instances: 1
mysql_monitor_instances: 1
clock_global_instances: 1
cloud_controller_worker_instances: 1
diego_database_instances: 1
diego_brain_instances: 1
diego_cell_instances: 3
doppler_instances: 1
loggregator_traffic_controller_instances: 1
tcp_router_instances: 1

## JMX Bridge tile configuration goes here
jmx_admin_usr: <CHANGE_ME>
jmx_admin_pwd: <CHANGE_ME>
jmx_security_logging: true
jmx_use_ssl: false
